### ISSUE TITLE
Importing very short and very long ITS1 regions into DB

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#135]
Currently the NCBI import (currently run recording at genus level only) will apply the HMM (built on the curated legacy dataset) for presence/absence, and trim accordingly to find the ITS1 region of interest. Sometimes this gives very short sequences (under 50bp) and sometimes very long (just over 1000bp in one case).

This is done by calling function ``thapbi_pict.hmm.filter_for_ITS1``,
https://github.com/peterjc/thapbi-pict/blob/v0.1.12/thapbi_pict/db_import.py#L275
https://github.com/peterjc/thapbi-pict/blob/v0.1.12/thapbi_pict/hmm/__init__.py#L101

The very short sequences are presumably a poor partial HMM match, and could be dropped with a minimum length threshold (will look at our curated set to set a sensible value).

The very long sequences are presumably the span of multiple HMM matches (some of which could be poor or borderline, but perhaps good), as per this stdout warning:

https://github.com/peterjc/thapbi-pict/blob/v0.1.12/thapbi_pict/hmm/__init__.py#L136

We might expect multiple tandem repeated ITS1 sequences to occur in a problematic genome, may want to take all the individual hits rather than their span?

The above approaches are tweaks to the HMM approach. We could consider doing in-silico PRC primer matching as an alternative?

See also #8.

**Comment by peterjc** [comment]
What should we do when a FASTQ read has multiple HMM matches? Currently where ``hmmscan`` is used (i.e. for every method except the ``blast`` classifier), we take the span there too. Should each match be assessed separately, and the union of their species predictions reported?

**Comment by peterjc** [comment]
Quick plot of the lengths in ``Phytophthora_ITS_database_v0.005.fasta ``

```
$ python -c "import sys; from Bio import SeqIO; print(''.join('%s\t%i\n' % (r.id, len(r)) for r in SeqIO.parse(sys.stdin, 'fasta')))" < Phytophthora_ITS_database_v0.005.fasta 
9_Phytophthora_fallax_Voucher_HQ261559	168
2a_Phytophthora_sp._aff._meadii_KC875839_2a_P._sp._mekongensis_type3_KM501564	145
7b_Phytophthora_cajani_AF266765	199
...
```

Copied into Excel,

![image](https://user-images.githubusercontent.com/63959/57535715-ab416d80-733a-11e9-8fa5-193b132ca537.png)

Min 136, Median 179.5, Max 203

Curated set length distribution does not look like a normal distribution. Might set limits as 100 to 250 as not too harsh?

**Comment by peterjc** [comment]
@widdowquinn suggests looking at the length distribution in the current DB, which will reflect what the current HMM is pulling out from larger sequences (our positive controls, and NCBI entries)

**Comment by peterjc** [comment]
Median about the same for the current unique DB sequences, but a long tail of short sequences - happily just a few very long entries.

```python
"""Length histogram of unique ITS1 sequences in database."""

from statistics import mode, median

import seaborn as sns

from thapbi_pict.__main__ import expand_database_argument
from thapbi_pict.db_orm import ITS1, connect_to_db


def main(db_url, debug=False):
    """Look for taxonomy conflicts."""
    # Connect to the DB,
    Session = connect_to_db(db_url, echo=False)
    session = Session()

    seqs = {_.sequence for _ in session.query(ITS1)}
    lengths = sorted(len(_) for _ in seqs)
    print("Min %i, max %i" % (min(lengths), max(lengths)))
    print("Mode %0.1f" % mode(lengths))
    print("Median %0.1f" % median(lengths))

    sns.set(color_codes=True)
    ax = sns.distplot(lengths)
    ax.set_xlim([0, 400])
    fig = ax.get_figure()
    fig.savefig("lengths.pdf")


if __name__ == "__main__":
    main(
        db_url=expand_database_argument("", exist=True, blank_default=True), debug=True
    )
```

```
$ python lengths.py
Min 28, max 1090
Mode 194.0
Median 178.0
```

[lengths.pdf](https://github.com/peterjc/thapbi-pict/files/3167200/lengths.pdf)

![image](https://user-images.githubusercontent.com/63959/57539521-949f1480-7342-11e9-8494-9b3b2b98fe38.png)

**Comment by peterjc** [comment]
For comparison, the legacy curated FASTA file once more but using Seaborne,

```
$ python -c "import sys; from statistics import median; import seaborn as sns; from Bio import SeqIO; L=[len(r) for r in SeqIO.parse(sys.stdin, 'fasta')]; print('Min %i, max %i, median %0.1f' % (min(L), max(L), median(L))); sns.set(color_codes=True); ax = sns.distplot(L); ax.set_xlim([0, 400]); ax.get_figure().savefig('lengths.pdf')" < Phytophthora_ITS_database_v0.005.fasta 
Min 136, max 203, median 180.0
```

![image](https://user-images.githubusercontent.com/63959/57540247-36733100-7344-11e9-91c0-ccb6dd16a0d3.png)

**Comment by widdowquinn** [comment]
The 100:250 limits look reasonable, but I might have thought to set the minimum to 130, to be a bit stricter. For bulk, non-curated imports I think we can afford to be exclusionary rather than inclusive by default.

I think we could probably treat length/other filters the same way we do code linting (but slightly stricter). By default we could set limits that do not import sequences into the reference database if they fall outwith the length restrictions, but warn the user and provide for two options to override the defaults:

1. set the limits with an argument in the command-line API (or function call)
2. mark individual sequences as exempt from the limit

(a third way, which would be the first thing I'd think of as a user, would be to extract the sequences I'm confident of having high quality into a separate file and import these with the revised argument - but that's the user's own choice)

**Comment by peterjc** [comment]
As of #138, the DB for v0.2.0 lengths:

```
$ python lengths.py
Min 100, max 234
Mode 194.0
Median 178.0
```

![image](https://user-images.githubusercontent.com/63959/57712600-c37df900-7668-11e9-8e1c-34ce584a6f0a.png)

**Comment by peterjc** [comment]
Looking at #139 (the effect of these changes on the classifier when it how has multiple HMM matches to consider), it seems at least some cases with overlapping partial HMM matches might after all be better handled by taking their span?

And/or we should look at updating the HMM itself with some curated non-*Phytophthora* entries?

**Comment by peterjc** [comment]
And/or supplement the *Phytophthora* HMM with additional genus-specific HMMs. This could include models for the synthetic controls too, potentially useful for more general QC questions.

**Comment by widdowquinn** [comment]
We should test empirically, but because the HMMs can cope with gaps I would expect that a single HMM would be sufficient for ITS1s.

We'd need 1 each for the synthetic controls, but an HMM might be overkill, as there's only one canonical example of each control.

**Comment by peterjc** [comment]
Yes, would need to explore pros and cons for extending single HMM for multiple genera, vs making genus specific HMMs.

And as discussed in person, yes, HMM would be overkill for finding each synthetic control (only need to capture PCR noise and sequencing error, no biological variation), but if we add code to cope with multiple HMMs, this makes looking for the synthetic controls trivially easy from a coding perspective - no special case required.

**Comment by widdowquinn** [comment]
Agreed.

**Comment by peterjc** [comment]
See #150 for using multiple HMM to also cover the synthetic controls.
