### ISSUE TITLE
QC module/functions for inspecting reference databases

### ISSUE THREAD

**Issue by widdowquinn** [peterjc/thapbi-pict#137]
It would be useful to have a module (maybe with cmd-line API) and functions to obtain summary information about a reference database. For example:

- distribution of sequence lengths
- clustering of sequences (in an "objective" way to see how "patchy" the data is, not with an attempt at classification)
- listing/identification of taxonomic class conflicts in identical sequences
- generation of phylogenetic trees of reference sequences (if, e.g. MUSCLE/RaxML installed)

**Comment by peterjc** [comment]
#135 is looking at length reporting, can see a role for that.

#18 was on QC and clustering. See also the ``graph`` branch although initially that was drawing edit graphs of reads from FASTA files

#136 has a script showing taxonomy conflicts

**Comment by peterjc** [comment]
I'm going to close this as all the example use cases are not relatively straight forward to achieve:

* distribution of sequence lengths -> generate plot from ``thapbi_pict dump`` output
* clustering of sequences (in an "objective" way to see how "patchy" the data is, not with an attempt at classification) -> use ``thapbi_pict edit-graph`` to visualise the clustering
* listing/identification of taxonomic class conflicts in identical sequences -> use ``thapbi_pict conflicts``
* generation of phylogenetic trees of reference sequences (if, e.g. MUSCLE/RaxML installed) -> generate FASTA with ``thapbi_pict dump`` and align that
