### ISSUE TITLE
Add standard copyright header to all the Python files

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#15]
Something like:

```python
# Copyright 2018 by Peter Cock, The James Hutton Institute.
# All rights reserved.
# This file is part of the THAPBI Phytophthora ITS1 Classifier Tool (PICT),
# and is released under the "MIT License Agreement". Please see the LICENSE
# file that should have been included as part of this package.
```

(Adjusted as appropriate for multiple contributions)

**Comment by widdowquinn** [comment]
I tend to include the copyright message in the file-level docstring, these days. Would there be an objection to adopting that style, here?

**Comment by peterjc** [comment]
No, that is near the start of the file so also very visible.

**Comment by peterjc** [comment]
Closed as of v0.3.0

**Comment by peterjc** [comment]
I opted not to put the copyright statement in the docstring, since it would then be very visible in the API docstrings, and a distraction to readability:

https://thapbi-pict.readthedocs.io/en/latest/api/index.html

**Comment by widdowquinn** [comment]
It's a judgement call and I'm happy with that.
