### ISSUE TITLE
Selecting sub-database by genus/species

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#16]
Currently we don't have a sub-database view, but the dump command would benefit from this.

**Comment by widdowquinn** [comment]
Options I'd like to see include:

- sub-database by:
  - species
  - data source
  - Phytophthora clade
  - sequencing strategy (where known)
  - sequencing platform (where known)
  - trust level
- filtering options
  - exclude sequences by trust level
  - exclude sequences from specific sources

**Comment by widdowquinn** [comment]
With an eye on database cross-validation, I would also like to generate (automatically) training/test/hold-out sets with these options.

As a first attempt, these can be of equal size (number of sequences), but in future releases we may want to allow an option to vary the proportion in each.

This may require use of a reduced cross-validation dataset, with respect to the complete database, as we would require at least one sequence from each validating species to be in each of the training/test/hold-out sets: only species with at least three sequences would qualify.

These species would then contribute a random, exclusive 1/3 of their sequences (near enough) to each of the training/test/hold-out sets. There will be some discussion necessary here about how to handle sampling bias (over-representation of sequences from some species), and redundant sequences (same ITS1 sequence from multiple isolates). It may be that we end up generating cross-validation sets from a reduced, non-redundant ITS1 database.

**Comment by peterjc** [comment]
At this point we don't plan to store the NCBI taxonomy parent/child relationship, so filtering by taxid (other than exact matches) is not going to be practical.

With the plans on #9 (pre-loading the NCBI taxonomy) and #17 to clean up our imported species name, we can use simple string matching for genus/species.

e.g. A list of genus names to look for:

```
$ thapbi_pict dump -g Phytophthora,Peronospora -d ...
```

(Initially of limited use while we are currently only importing *Phytophthora* into the database)

If restricting to a single genus, then a list of species names might work like this:

```
$ thapbi_pict dump -g Phytophthora -s "ilicis, sp. aff. meadii" -d ...
```

Or, for more flexibility a list of genus-species names to look for, e.g.

```
$ thapbi_pict dump -n "Phytophthora ilicis, Phytophthora sp. aff. meadii, Peronospora alta" -d ...
```

Taking the names from a simple text file might actually prove more usable (one entry per line)?

(Examples shown with white space after the comma for multiple names - would be unambiguous and simple to support, and aids legibility)

This already supports filtering by clade, although with current usage this is implicitly *Phytophthora* specific.

```
$ thapbi_pict dump -c 8a,8b -d ...
```

**Comment by widdowquinn** [comment]
Not for the first version, but something like:

```
$ thapbi_pict dump -g Phytophthora -s "ilicis, sp. aff. meadii" -d ...
```

and 

```
$ thapbi_pict dump -g Phytophthora -s my_species.txt -d ...
```

could be very useful!

**Comment by widdowquinn** [comment]
The `dump` command sounds appropriate, but generic: are we dumping SQL, `.tab`, or FASTA?

Either:

```
$ thapbi_pict dump
$ thapbi_pict dump_sql
$ thapbi_pict dump_fasta
$ thapbi_pict dump_tab
```

or 

```
$ thapbi_pict dump --formats sql,fasta,tab
```

would be fine with me.

**Comment by peterjc** [comment]
Dump output formats logged as #19.
