### ISSUE TITLE
Track DB under version control, but not as SQL?

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#483]
The history of this file is not usually helpful, as even 'small' changes like taxonomy additions renumber all the taxonomic table IDs which makes a massive diff, as would even adding a single sequence (if early in the order):

https://github.com/peterjc/thapbi-pict/blob/master/database/ITS1_DB.sql

Rather the TSV dump format would be more useful, which has these columns:

1.   Marker, e.g. ITS1
2.   Identifier
3.   Genus
4.   Species
5.   TaxID
6.   MD5
7.   Sequence, trimmed to the amplicon only

For some time now ``database/build_ITS-DB.sh`` should work from a clean git checkout, so it is not essential to be able to go from the version-tracked dump to a working SQLite3 DB. However, ideally would be able to import the TSV dump (perhaps after loading the NCBI taxonomy; would have to be after defining amplicon(s) and their primers), with the proviso this would loose information like the original source filenames.

**Comment by peterjc** [comment]
As noted on #484, this has implications for how the CI bootstraps itself.

**Comment by peterjc** [comment]
Example commit https://github.com/peterjc/thapbi-pict/commit/63802e9fa1c5674185dde7248220c297b02a3ac8 shows the easily interpreted TSV diff from a rebased version of #485 on top of #484.

**Comment by peterjc** [comment]
@widdowquinn if you have a moment this week, what are your thoughts on this issue about tracking the history of the THAPBI PICT database (we already track the inputs and code which builds the database)?

**Comment by peterjc** [comment]
Even simpler, perhaps we don't need to record the DB changes under version control at all now, given the build is fully reproducible from the git repository?

**Comment by widdowquinn** [comment]
If the inputs and code are sufficient to generate the database, then I agree it would be redundant to track the database as well.

If users download - rather than generate for themselves - a database for local use, and we wanted to link that sort of thing explicitly, then a compiled version at Zenodo with DOI might be a better option than tracking at GitHub. This is still redundant, but if the redundancy simplifies/eases user workflow maybe it's worth it?

**Comment by peterjc** [comment]
Thank Leighton.

We could decouple the DB releases from the Tool releases, at which point a separate Zenodo entry makes sense (perhaps on top of a separate DB only GitHub repository), but there have been schema changes so the current approach seems fine for the time being...

**Comment by peterjc** [comment]
#484 switches to tracking the TSV dump.

#486 switches to tracking the FASTA dump (including taxid), with a retrospective history of changes since v0.10.0 showing how the diffs are useful.

In either case, the human readable dump is valuable (including to external parties who may not want to run the code or use SQLite3), and the CI can verify that rebuilding the DB (required for bootstrapping) still gives the expected DB dump.
