### ISSUE TITLE
Problem with using downloaded EMBL nucleotide database

### ISSUE THREAD

**Issue by shamba123** [peterjc/thapbi-pict#650]
Hello,
   I am trying to do a dietary metabarcoding project on carnivores, similar to the Obitools tutorial described. I have downloaded nucleotide database data from EMBL and taxonomic information from NCBI. After using obiconvert for building an ecoPCR database, I notice following file types: embl_data.ndx, embl_data.tdx, embl_data.rdx, embl_data.adx and embl_data.sdx files. However, there is no .pdx file created. In the following steps, when I run the ecotag command with the result of ecoPCR command on selected primers, an output file gets created with the error log: Local taxon file not found; No such file or directory: 'embl_data.pdx'. I looked up, and found that the pipeline usually gets run even without a .pdx file, however my output is devoid of any information like family, genus names. 
sample code: 
OBICONVERT: obiconvert --embl -t /blue/baer/s.basu/Diet_Test_Run/trimmed_reads/clean_data --ecopcrdb-output=embl_data /blue/baer/s.basu/Diet_Test_Run/trimmed_reads/EMBL_data/std/*.dat --skip-on-error
 ECOPCR: ecoPCR -d /blue/baer/s.basu/Diet_Test_Run/trimmed_reads/12S_vrt_test/12S_vrt_custom -e 3 -l 50 -L 150 TTAGATACCCCACTATGC TAGAACAGGCTCCTCTAG > primer_t1.ecopcr

Is there any particular command for creating the .pdx file? what is the local taxon file required here?

**Comment by peterjc** [comment]
I think you are looking at the wrong repository, although potentially my metabarcoding pipeline might be useful to you.

Perhaps https://github.com/metabarcoding/obitools4 depending on which version of OBI Tools you are using?

**Comment by shamba123** [comment]
I am using obitools version 1.2.13 on python based shell environment. In the server environment I have access to obitools version3, but there is some problem with the way the way the updated version works. Should I switch to obitools 4 for executing the pipeline?

**Comment by peterjc** [comment]
If you are using obitools v1, I think the repository is https://git.metabarcoding.org/obitools/obitools - but this hasn't been updated in years.

I'm not familiar with the changes the authors have made, but would certainly think starting with v3 or the current v4 makes more sense than fighting with the obsolete v1.

**Comment by peterjc** [comment]
I don’t know.

To repeat myself but more clearly: I have no connection to OBI Tools. You are commenting on the issue tracker for a completely different metabarcoding pipeline (called THAPBI PICT).
