### ISSUE TITLE
Review left primer trimming

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#85]
Originally we hard trimmed 53bp of the start, made up of a 21bp primer GAAGGTGAAGTCGTAACAAGG and 32bp conserved sequence TTTCCGTAGGTGAACCTGCGGAAGGATCATTA.

This was recently refined to trim 52 or 54bp is there was a deletion or insertion in the expected sequence.

Finally yesterday in #84, if the expected primer+conserved sequence is not found (allowing 1bp substitution, deletion or insertion), we drop the sequence completely.

This may introduce a bias as will now discard otherwise potentially informative sequences if they have SNPs etc in the conserved region.

Probably the best option here is to only trim the 21bp primer, and include the generally conserved 32bp region of 18S in our database.

**Comment by peterjc** [comment]
Discussed with @widdowquinn, miscommunication yesterday about discarding sequences if the primers don't match - in that context he understood just the 21bp left primer (and 20bp right primer). Doing that we shouldn't have the bias I was worrying about overnight.

We agreed it would be worth looking at the 32bp conserved region.

**Comment by peterjc** [comment]
Running the current code on our main control plate, it is clear that rejecting sequences which lack either the 21bp left or 20bp right primer, discards a lot of usable sequences with clearly recognised ITS1 sequences.

i.e. The original approach of cutting off the expected primer length even if it wasn't a close match may work better overall.

TODO: Try this with an external primer trimming tool like ``cutadapt`` #82

**Comment by peterjc** [comment]
Note to self: Stop writing new diagnostic failed primer FASTA file by default.

Have created ``Undetermined_S0_L001.failed-primers.fasta`` (from reads which failed barcode demultiplexing) of over 1GB in size, and over 2.5 million unique sequences.

**Comment by widdowquinn** [comment]
How lenient does the primer sequence matching (e.g. with cutadapt) have to be before it approaches the same result as cutting the primer on the basis of sequence length? And can cutadapt/another tool identify primers at that distance.

One way to approach this, for which you might already have the data, is to align each unique (trimmed) primer region sequence and assess the sequence variation.

**Comment by peterjc** [comment]
I don't have a side by side comparison of the current Python 1bp difference code with cutadapt, but plan that. One of the reasons for writing the failed primer FASTA files is to facilitate inspecting the divergent sequences for undetected primers.

**Comment by peterjc** [comment]
Closing, cross reference #90 and #96.
