### ISSUE TITLE
Set default abundance threshold based on plates to date?

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#94]
From approx ten plates including control plates, we now have about 40 samples of the G-BLOCKS synthetic controls sequenced, all of which should all have no ITS1 sequence in them.

We could therefore look at the distribution of ITS1 reads here, and use this to set a more informed plate level default abundance threshold (currently 100).

Currently most of the control samples have below the current default threshold (of 100 reads), less than a quarter exceed this - so the median maximum contaminant abundance is indeed at most 100.

Note: As of 0593f5c3638890ed2f056493c9f08acf6a20c37b we no longer report all the contaminants in the control FASTA files (since these were not of interest and wasted compute time when running the classifiers on the controls). Closer examination would require running ``thapbi-pict prepare-reads -a 0 ...`` on the control samples.

**Comment by peterjc** [comment]
Try median of non-zero maximum ITS1 abundance values in G-BLOCK controls.

**Comment by peterjc** [comment]
Or, try varying the threshold on the control plate (ignoring what we'd pick from the G-BLOCK control), and try to minimise ad-hoc loss score or otherwise.

**Comment by peterjc** [comment]
Assuming no mistakes in the symlink creation (which is possible as we didn't have consistent naming on the controls, and in one collaborator's plate a prefix was used for real data), here are all the maximum abundances from each 49 G-Blocks control samples to date (our negative controls):

```
[4, 5, 6, 6, 6, 6, 7, 7, 8, 9, 10, 10, 11, 11, 12, 12, 14, 14, 14, 15, 16, 16, 17, 19,
 20, 20, 21, 22, 25, 26, 26, 27, 28, 29, 31, 42, 44, 54, 57, 90, 107, 107, 143, 144,
 217, 229, 385, 545, 1496]
Mean of max-abundance 85.5
Median of max-abundance 20
N50 of max-abundance 385.0
```

Or another metric, a threshold of:

```
>>> x = [4, 5, 6, 6, 6, 6, 7, 7, 8, 9, 10, 10, 11, 11, 12, 12, 14, 14, 14, 15, 16, 16, 17, 19, 20, 20, 21, 22, 25, 26, 26, 27, 28, 29, 31, 42, 44, 54, 57, 90, 107, 107, 143, 144, 217, 229, 385, 545, 1496]
>>> for t in [50, 100, 150, 200, 250, 300, 400]:
...     a = [_ for _ in x if _ < t]
...     b = [_ for _ in x if _ >= t]
...     print("With %i as threshold, %0.1f%% below and %0.1f%% above" % (t, len(a) * 100.0 / len(x), len(b) * 100.0 / len(x)))
... 
With 50 as threshold, 75.5% below and 24.5% above
With 100 as threshold, 81.6% below and 18.4% above
With 150 as threshold, 89.8% below and 10.2% above
With 200 as threshold, 89.8% below and 10.2% above
With 250 as threshold, 93.9% below and 6.1% above
With 300 as threshold, 93.9% below and 6.1% above
With 400 as threshold, 95.9% below and 4.1% above
```

**Comment by widdowquinn** [comment]
Interesting…

```python
import seaborn as sns

x = [4, 5, 6, 6, 6, 6, 7, 7, 8, 9, 10, 10, 11, 11, 12, 12, 14, 14, 14, 15, 16, 16, 17, 19,
 20, 20, 21, 22, 25, 26, 26, 27, 28, 29, 31, 42, 44, 54, 57, 90, 107, 107, 143, 144,
 217, 229, 385, 545, 1496]

ax = sns.kdeplot(x)
ax.set_xlim(0, 200)
```

If I was fitting a Gaussian, I'd probably expect a suitable threshold to sit at around 50 (liberal) or 100 (conservative)

![download](https://user-images.githubusercontent.com/63981/55094643-aee0a400-50ae-11e9-968f-6392a14ee158.png)

**Comment by peterjc** [comment]
Closing issue (for now), based on the current data, the current default of 100 while perhaps a little conservative is a reasonable choice.
