### ISSUE TITLE
(All) sample level reporting

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#99]
We need another summary command which works at sample level, proposal is to produce at computer readable table of five columns:

```
1. Sample name (from filename stem)
2. NCBI taxid, e.g. 4787
3. Species name, e.g. *Phytophthora infestans*
4. Unambiguous classification, True or False
5. Total sequence count
```

For example, given a sample level output of:

```
XXXXXX_5000 	4787;283007;283009	Phytophthora infestans;Phytophthora ipomoeae;Phytophthora andina
YYYYYY_2000	4787	Phytophthora infestans
ZZZZZZ_1000 	4787;283007	Phytophthora infestans;Phytophthora ipomoeae
```

Here XXXXXX, YYYYYY and ZZZZZZ represent arbitrary MD5 checksums. Here there were 5000 reads which matched the trio of species, 1000 for a pair, and 2000 which were clearly classified as *Phytophthora infestans* only. This would contribute:

```
SAMPLE1	4787	Phytophthora infestans	True	2000
SAMPLE1	4787	Phytophthora infestans	False	6000
SAMPLE1	283007	Phytophthora ipomoeae	False	6000
SAMPLE1	283009	Phytophthora andina	False	5000
```

It would perhaps make sense to include an additional line for any unclassified reads, in part to ensure all the samples appear in this output.

Additionally, we want a human readable output which only reports the species identified in each sample (perhaps using brackets when a species was only called ambiguously), e.g.

```
SAMPLE1	Phytophthora infestans
SAMPLE1	(Phytophthora ipomoeae)
SAMPLE1	(Phytophthora andina)
SAMPLE2	No species predicted
```

Or perhaps if using a rich text format:

> SAMPLE1
>  - *Phytophthora infestans*
>  - (*Phytophthora ipomoeae*)
>  - (*Phytophthora andina*)
>
> SAMPLE2
>  - No species predicted

Currently we have ``thapbi_pict plate-summary`` which works at sequence-level (typically at plate level, but can be used on multiple plates):

```
$ thapbi_pict plate-summary -h
usage: thapbi_pict plate-summary [-h] [-m METHOD] [-a ABUNDANCE] [-o FILENAME]
                                 [-v]
                                 inputs [inputs ...]

Sequence-level summary report on classifier output.

...

Assumes you've run prepare-reads and classify, and have folders with XXX.fasta
and XXX.method.tsv files from your plate(s). The output is a table with one
row per unique sequence (as trimmed by the prepare-reads step, can be 1000s of
rows) and one column per sample (typically 96 samples).
```

This new command could be ``thapbi_pict sample-summary``, and we would want to be able to run it on multiple plates at once.

**Comment by widdowquinn** [comment]
Hard yes to the line indicating the count of unclassified reads.

**Comment by widdowquinn** [comment]
FWIW, I still think we're pushing the limits of the envelope of acceptability by reporting the taxonomically-conflicted sequences *at all*. I'd be more comfortable if we didn't.

**Comment by peterjc** [comment]
I have toyed with the idea of merging those entries with identical ITS, so we could have the trio of *Phytophthora infestans*, *Phytophthora ipomoeae* and *Phytophthora andina* treated as a single pseudo-species, as an alternative to the current behaviour of reporting them all. However, if we don't report these at all, it means being unable to report an uncomfortably large number of species.

Separately, with the fuzzy classifiers like ``onebp`` or ``blast`` etc, we have the additional situation of the sample's sequence being an equal distance from two (or more) distinct database sequences (e.g. one base pair edit away, or equal BLAST scores). Here certainly we could choose to report neither (falling between two stools). I'm not sure off hand how common this is. File as a separate issue?

**Comment by peterjc** [comment]
I've added some sample output to the PR comments, highlighting a result with an ``Unknown`` classification, and how the DB content can affect the uniqueness of the call with the *Phytophthora infestans* prediction vs the *P. ipomoeae* and *P. andina* "doppelgängers" which share some of the same ITS1 sequences in the DB.

https://github.com/peterjc/thapbi-pict/pull/100#issuecomment-477091901

**Comment by widdowquinn** [comment]
> "if we don't report these at all, it means being unable to report an uncomfortably large number of species."

We have different levels and points of discomfort ;) Ultimately, we're going to be led with what the wet-lab/nursery people want in terms of information. I think they will want the level of control over interpretation that you suggest. I'm OK with strongly flagging uncertainty, and *why* we're uncertain, making clear that any action taken on the basis of those predictions is entirely at the risk of the interpreter.

> "Phytophthora infestans, Phytophthora ipomoeae and Phytophthora andina treated as a single pseudo-species"

I think we will be asked to explain precisely what this means, and what we will say is that the reads could support the presence of any or all of these organisms, but we can't tell in what combination. Then if there's any other conflicted identification, e.g. {P. infestans, P. ipomoeae} identified as its own pseudospecies, we'll be asked to justify that definition, too.

Reporting "P. infestans (ambiguous/uncertain)", "P. ipomoeae (ambiguous/uncertain)", and "P. andina (ambiguous/uncertain)" as three different classes cuts across the need to define new pseudospecies, and makes clear exactly what the classifier's diagnosis is. Also, where a single "uncertain" identifier also has large unambiguous read support, and the ambiguous read count dwarfs the - say - P. andina ambiguous reads, it gives enough information to the interpreter to say that P. andina is on balance of probability not present.

> "Here certainly we could choose to report neither (falling between two stools). I'm not sure off hand how common this is. File as a separate issue?"

I'd say this is a separate issue: Enhancement - implement a Bayesian classifier ;)

**Comment by peterjc** [comment]
For the human readable output are you suggesting changing “(species)” to “species (uncertain/ambiguous)”? That does seem more explicit

**Comment by widdowquinn** [comment]
I wasn't, but if it's a good idea I'll take credit ;)

**Comment by peterjc** [comment]
#100 merged, first iteration of this done.
